$(document).ready(function(){
    var x=0;
    var y=".s";
    $(".s1").click(function(){
        $("#v1").addClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/LloydPrice.jpg)")
        $("#music").attr('src','mp3/StaggerLee.m4a')
        x=1;
    });

    $(".s2").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").addClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/BobbyDarin.jpg)")
        $("#music").attr('src','mp3/DreamLover.ogg')
        x=2;
    });

    $(".s3").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").addClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/BenEKing.jpg)")
        $("#music").attr('src','mp3/StandByMe.ogg')
        x=3;
    });

    $(".s4").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").addClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Elvis.jpg)")
        $("#music").attr('src','mp3/BlueSuedeShoes.m4a')
        x=4;
    });

    $(".s5").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").addClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Franky.jpg)")
        $("#music").attr('src','mp3/EyesOffYou.m4a')
        x=5;
    });

    $(".s6").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").addClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Danleers.jpg)")
        $("#music").attr('src','mp3/SummerNight.m4a')
        x=6;
    });

    $(".s7").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").addClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Penguins.jpg)")
        $("#music").attr('src','mp3/EarthAngel.m4a')
        x=7;
    });

    $(".s8").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").addClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/CurtisLee.jpg)")
        $("#music").attr('src','mp3/AngelEyes.m4a')
        x=8;
    });

    $(".s9").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").addClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Dion.jpg)")
        $("#music").attr('src','mp3/Teenager.ogg')
        x=9;
    });

    $(".s10").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").addClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Paul.jpg)")
        $("#music").attr('src','mp3/Shoulder.ogg')
        x=10;
    });

    $(".s11").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").addClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Fats.jpg)")
        $("#music").attr('src','mp3/Shame.m4a')
        x=11;
    });

    $(".s12").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").addClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Everly.jpg)")
        $("#music").attr('src','mp3/Dream.m4a')
        x=12;
    });

    $(".s13").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").addClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/BobbyDarin.jpg)")
        $("#music").attr('src','mp3/Sea.ogg')
        x=13;
    });

    $(".s14").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").addClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Monotones.jpg)")
        $("#music").attr('src','mp3/Book.m4a')
        x=14;
    });

    $(".s15").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").addClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Buddy.jpg)")
        $("#music").attr('src','mp3/OhBoy.m4a')
        x=15;
    });

    $(".s16").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").addClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Chuck.jpg)")
        $("#music").attr('src','mp3/NoPlace.ogg')
        x=16;
    });

    $(".s17").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").addClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Dion1.jpg)")
        $("#music").attr('src','mp3/SweetHearts.m4a')
        x=17;
    });

    $(".s18").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").addClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Doris.jpg)")
        $("#music").attr('src','mp3/JustOneLook.m4a')
        x=18;
    });

    $(".s19").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").addClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Elvis.jpg)")
        $("#music").attr('src','mp3/Shook.m4a')
        x=19;
    });

    $(".s20").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").addClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Elvis1.jpg)")
        $("#music").attr('src','mp3/FallingInLove.m4a')
        x=20;
    });

    $(".s21").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").addClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Elvis.jpg)")
        $("#music").attr('src','mp3/FollowDream.ogg')
        x=21;
    });

    $(".s22").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").addClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Richard.jpg)")
        $("#music").attr('src','mp3/Lucille.m4a')
        x=22;
    });

    $(".s23").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").addClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Clovers.jpg)")
        $("#music").attr('src','mp3/LovePotion.m4a')
        x=23;
    });

    $(".s24").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").addClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Chordettes.jpg)")
        $("#music").attr('src','mp3/Sandman.m4a')
        x=24;
    });

    $(".s25").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").addClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Crests.jpg)")
        $("#music").attr('src','mp3/StepByStep.ogg')
        x=25;
    });

    $(".s26").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").addClass("opacityOne");
        $("#v27").removeClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Drifters.jpg)")
        $("#music").attr('src','mp3/Boardwalk.m4a')
        x=26;
    });

    $(".s27").click(function(){
        $("#v1").removeClass("opacityOne");
        $("#v2").removeClass("opacityOne");
        $("#v3").removeClass("opacityOne");
        $("#v4").removeClass("opacityOne");
        $("#v5").removeClass("opacityOne");
        $("#v6").removeClass("opacityOne");
        $("#v7").removeClass("opacityOne");
        $("#v8").removeClass("opacityOne");
        $("#v9").removeClass("opacityOne");
        $("#v10").removeClass("opacityOne");
        $("#v11").removeClass("opacityOne");
        $("#v12").removeClass("opacityOne");
        $("#v13").removeClass("opacityOne");
        $("#v14").removeClass("opacityOne");
        $("#v15").removeClass("opacityOne");
        $("#v16").removeClass("opacityOne");
        $("#v17").removeClass("opacityOne");
        $("#v18").removeClass("opacityOne");
        $("#v19").removeClass("opacityOne");
        $("#v20").removeClass("opacityOne");
        $("#v21").removeClass("opacityOne");
        $("#v22").removeClass("opacityOne");
        $("#v23").removeClass("opacityOne");
        $("#v24").removeClass("opacityOne");
        $("#v25").removeClass("opacityOne");
        $("#v26").removeClass("opacityOne");
        $("#v27").addClass("opacityOne");
        $(".portrait").css("background-image","url(./images/Platters.jpg)")
        $("#music").attr('src','mp3/OnlyYou.ogg')
        x=27;
    });


    var isRandom=0;

    $('audio').on('ended',function(){
        if(isRandom==0){
            x=x+1
            var z=y+x;
            $(z).trigger('click');
            console.log(x)
            if(x==27){
                x=0;
            }
        }else{
            var random;
            random = Math.ceil(Math.random() * 27)
            z=y+random;
            $(z).trigger('click');
            console.log(x)
        }
    });

    $(".randomToggle").click(function(){
        if(isRandom==0){
            isRandom=1;
            console.log("RANDOM")
            $(".fa-random").css("color","red")
        }else{
            isRandom=0;
            console.log("NOT-RANDOM")
            $(".fa-random").css("color","#269bff")
        }
    });
    
//Forwards Control    
    $(".controlForward").click(function(){
        if(isRandom==0){
            if(x==27){
                console.log("Forward-Wrap");
                x=1;
                var z=y+x;
                $(z).trigger('click');
                console.log(z)
            }else{
                console.log("Forward");
                x++
                var z=y+x;
                $(z).trigger('click');
                console.log(z)
            }
        }else{
            console.log("Forward-Random");
            var random;
            random = Math.ceil(Math.random() * 27)
            z=y+random;
            $(z).trigger('click');
            console.log(z)                
            }
      });
    
//Backwards Control    
    $(".controlBackward").click(function(){
        if(isRandom==0){
            if(x<=1){
                x=27;
                var z=y+x;
                $(z).trigger('click');
                console.log("Backward-Wrap");
                console.log(z)  
            }else{
                console.log("Backward");
                x--
                var z=y+x;
                $(z).trigger('click');
                console.log(z)
            }

        }else{
            console.log("Backward-Random");
            var random;
            random = Math.ceil(Math.random() * 27)
            z=y+random;
            $(z).trigger('click');
            console.log(z)                
            }
      });    
});